### ISSUE TITLE
https://github.com/kevinbaross/custom_indexing_project/tree/streamlit_ux_custom_index

### ISSUE THREAD

**Issue by sidbetatester** [kevinbaross/custom_indexing_project#2]
Hi Kevin and  Haoyu, 

I have updated the code and  just uploaded to git branch. 

Kevin(Our group) and I discussed earlier I added the comments with 'To Do's' in each file,  I guess we have a good structure now for the streamlit app, please review the 'To Do' comments and let me know if you have any questions.

Hi  Chris and  Hugo, 
Please share your feedback as well, Kevin and Haoyu will need the dataframes/series to complete next steps. they may be able to manage with sample dataframes if we need more time cleaning the datasets.

**Comment by chdi2942** [comment]
All To Do's have been completed and filters have been perfected and tested.  Closing ticket.
